import { useEffect, useMemo, useRef, useState } from "react";
import { api, upload } from "../../api/client";
import { Avatar } from "../../components/Avatar";
import { DialogHeader, Modal } from "../../components/Modal";
import type { Category, Expense, OcrResponse, Trip, User } from "../../types/models";
import { formatMoney, kronorToOre } from "../../utils/format";
import { receiptAiStatus, validateReceiptImage } from "../receipts/ocr";
import { prepareReceiptFile } from "../receipts/imagePrep";

type SplitMode = "equal" | "percentage" | "exact" | "shares";
interface Values { title: string; amount: string; payerId: string; expenseDate: string; category: string; splitMode: SplitMode }

export function ExpenseDialog({ open, trip, categories, expense, user, onClose, onSaved, onManageCategories, notify }: { open: boolean; trip: Trip; categories: Category[]; expense: Expense | null; user: User; onClose: () => void; onSaved: () => Promise<void>; onManageCategories: () => void; notify: (message: string) => void }) {
  // Default "Betalat av" to whoever is actually adding the expense, not just the trip's first
  // participant -- otherwise it silently stays on the trip creator for everyone else.
  const defaultPayerId = trip.participants.find((participant) => participant.userId === user.id)?.id ?? trip.participants[0]?.id;
  const initial = useMemo<Values>(() => ({ title: expense?.title || "", amount: expense ? (expense.amountCents / 100).toFixed(2).replace(".", ",") : "", payerId: String(expense?.payerId || defaultPayerId || ""), expenseDate: expense?.expenseDate || "", category: expense?.category || "other", splitMode: expense ? expense.splitMode : "equal" }), [expense, defaultPayerId]);
  const [values, setValues] = useState(initial); const [selected, setSelected] = useState<Set<number>>(new Set()); const [splitValues, setSplitValues] = useState<Record<number, string>>({}); const [receipt, setReceipt] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [status, setStatus] = useState("Du granskar alltid förslagen innan utgiften sparas."); const [statusClass, setStatusClass] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const scanController = useRef<AbortController | null>(null); const scanGeneration = useRef(0);
  useEffect(() => {
    if (!open) return; setValues(initial); const chosen = new Set(expense?.shares.map((share) => share.participantId) || trip.participants.map((participant) => participant.id)); setSelected(chosen); const next: Record<number, string> = {}; expense?.shares.forEach((share) => { next[share.participantId] = (share.amountCents / 100).toFixed(2).replace(".", ","); }); setSplitValues(next); setReceipt(null); setPreview(""); setStatus("Du granskar alltid förslagen innan utgiften sparas."); setStatusClass(""); setError("");
  }, [open, initial, expense, trip.participants]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  const activeCategories = categories.filter((category) => !category.archivedAt || category.slug === values.category);
  const changeMode = (mode: SplitMode) => {
    const count = Math.max(selected.size, 1); const amountCents = kronorToOre(values.amount); const ids = [...selected]; const next: Record<number, string> = {};
    ids.forEach((id, index) => { if (mode === "shares") next[id] = "1"; else if (mode === "percentage") { const base = Math.floor(10000 / count) / 100; next[id] = (index === ids.length - 1 ? 100 - base * (ids.length - 1) : base).toFixed(2).replace(".", ","); } else if (mode === "exact" && amountCents) { const base = Math.floor(amountCents / count); next[id] = ((index === 0 ? base + amountCents - base * count : base) / 100).toFixed(2).replace(".", ","); } });
    setValues((current) => ({ ...current, splitMode: mode })); setSplitValues(next);
  };
  const analyze = async (file?: File) => {
    if (!file) return; const validation = validateReceiptImage(file); if (validation) { setStatus(validation); setStatusClass("warning"); return; }
    scanController.current?.abort(); const controller = new AbortController(); scanController.current = controller; const generation = ++scanGeneration.current;
    setStatusClass("reading"); setStatus("Förbereder bild…");
    let prepared: File;
    try { prepared = await prepareReceiptFile(file, (message) => { if (!controller.signal.aborted && generation === scanGeneration.current) setStatus(message); }); }
    catch (caught) { if (!controller.signal.aborted && generation === scanGeneration.current) { setStatusClass("warning"); setStatus(caught instanceof Error ? caught.message : "Kunde inte förbereda kvittobilden."); } return; }
    if (controller.signal.aborted || generation !== scanGeneration.current) return;
    if (preview) URL.revokeObjectURL(preview); setReceipt(prepared); setPreview(URL.createObjectURL(prepared)); setStatusClass("reading"); setStatus("Den lokala OCR-tjänsten läser och kontrollerar kvittot…");
    try { const signal = AbortSignal.any([controller.signal, AbortSignal.timeout(30_000)]); const payload = await upload<OcrResponse>(`/api/trips/${trip.id}/receipts/analyze`, prepared, {}, signal); if (generation !== scanGeneration.current) return; const suggestion = payload.suggestion || {}; setValues((current) => ({ ...current, title: suggestion.title || current.title, amount: suggestion.amount || current.amount, expenseDate: suggestion.expenseDate || current.expenseDate, category: suggestion.category && categories.some((category) => category.slug === suggestion.category) ? suggestion.category : current.category })); const found = [suggestion.title, suggestion.amount, suggestion.expenseDate].filter(Boolean).length; const engine = payload.source === "rapidocr" ? "lokal dokument-OCR" : "lokal reserv-OCR"; setStatusClass(found ? "success" : "warning"); setStatus(found ? `Förslag ifyllda med ${engine} (${payload.confidence || 0}% läskvalitet).${receiptAiStatus(payload.ai)}${payload.needsReview ? " Kontrollera extra noga." : " Kontrollera namn, belopp och datum innan du sparar."}` : "Kvittot bifogas, men texten kunde inte läsas tydligt. Fyll i uppgifterna manuellt."); }
    catch (caught) { if (controller.signal.aborted || generation !== scanGeneration.current) return; setStatusClass("warning"); setStatus(`${caught instanceof Error && caught.name !== "TimeoutError" ? caught.message : "Kvittoanalysen tog för lång tid"} Kvittot kan fortfarande bifogas.`); }
  };
  const close = () => { scanController.current?.abort(); scanGeneration.current += 1; if (preview) URL.revokeObjectURL(preview); onClose(); };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (busy) return; setError(""); setBusy(true); const entries = [...selected].map((participantId) => ({ participantId, value: values.splitMode === "equal" ? 1 : splitValues[participantId] || 0 }));
    try { const path = expense ? `/api/expenses/${expense.id}` : `/api/trips/${trip.id}/expenses`; const payload = await api<{ expenseId?: number }>(path, { method: expense ? "PATCH" : "POST", body: { ...values, entries } }); let receiptFailed = false; if (!expense && receipt && payload.expenseId) { setStatusClass("reading"); setStatus("Laddar upp kvittot…"); try { await upload(`/api/expenses/${payload.expenseId}/receipts`, receipt, { "X-File-Name": encodeURIComponent(receipt.name || "kvitto.jpg") }); setStatusClass("success"); setStatus("Kvittot sparades."); } catch { receiptFailed = true; } } await onSaved(); close(); notify(receiptFailed ? "Utgiften sparades, men kvittot kunde inte bifogas. Lägg till det under utgiften." : expense ? "Utgiften uppdaterades" : receipt ? "Utgiften och kvittot sparades" : "Utgiften delades exakt på öret"); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Kunde inte spara utgiften"); }
    finally { setBusy(false); }
  };
  const summaryTotal = [...selected].reduce((sum, id) => sum + Number(String(splitValues[id] || 0).replace(",", ".")), 0);
  return <Modal open={open} onClose={close} wide><form onSubmit={submit}><DialogHeader eyebrow={expense ? "Uppdatera notan" : "Lägg till på notan"} title={expense ? "Redigera utgift" : "Ny utgift"} onClose={close} />{!expense && <section className="receipt-capture"><div className="receipt-capture-copy"><strong>Skapa från kvitto</strong><small>Ta ett nytt foto eller välj en befintlig bild. Appen föreslår plats, totalbelopp och datum.</small></div><div className="receipt-actions"><label className="button dark receipt-camera-button">▣ Ta foto<input type="file" accept="image/*" capture="environment" hidden onChange={(event) => void analyze(event.target.files?.[0])} /></label><label className="button ghost receipt-camera-button">Välj bild<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={(event) => void analyze(event.target.files?.[0])} /></label></div>{preview && <div className="receipt-preview"><img src={preview} alt="Förhandsvisning av kvitto" /><button className="button ghost small-button" type="button" onClick={() => { URL.revokeObjectURL(preview); setPreview(""); setReceipt(null); }}>Ta bort kvittot</button></div>}<p className={`receipt-status ${statusClass}`} aria-live="polite">{status}</p></section>}
    <div className="form-row unequal"><label className="grow">Restaurang, plats eller vad köptes?<input value={values.title} onChange={(event) => setValues((current) => ({ ...current, title: event.target.value }))} maxLength={100} required /></label><label>Belopp (SEK)<input type="text" inputMode="decimal" placeholder="249,50" value={values.amount} onChange={(event) => setValues((current) => ({ ...current, amount: event.target.value.replace(/[^0-9,.]/g, "") }))} required /></label></div><div className="form-row"><label>Betalat av<select value={values.payerId} onChange={(event) => setValues((current) => ({ ...current, payerId: event.target.value }))} required>{trip.participants.map((participant) => <option key={participant.id} value={participant.id}>{participant.name}</option>)}</select></label><label>Datum <small>Valfritt</small><input type="date" value={values.expenseDate} onChange={(event) => setValues((current) => ({ ...current, expenseDate: event.target.value }))} /></label><div className="category-field"><label>Kategori<select value={values.category} onChange={(event) => setValues((current) => ({ ...current, category: event.target.value }))}>{activeCategories.map((category) => <option value={category.slug} key={category.id}>{category.emoji} {category.name}{category.archivedAt ? " (arkiverad)" : ""}</option>)}</select></label><button className="text-button category-manage" type="button" onClick={onManageCategories}>Hantera kategorier</button></div></div>
    <fieldset><legend>Fördela</legend><div className="segmented">{(["equal", "percentage", "exact", "shares"] as SplitMode[]).map((mode) => <label key={mode}><input type="radio" name="splitMode" checked={values.splitMode === mode} onChange={() => changeMode(mode)} /><span>{mode === "equal" ? "Lika" : mode === "percentage" ? "Procent" : mode === "exact" ? "Exakt SEK" : "Andelar"}</span></label>)}</div></fieldset>
    <div className="split-select-toggle"><button type="button" className="text-button" onClick={() => setSelected(new Set(trip.participants.map((participant) => participant.id)))}>Välj alla</button><button type="button" className="text-button" onClick={() => setSelected(new Set())}>Avmarkera alla</button></div>
    <div className="split-people">{trip.participants.map((participant, index) => { const checked = selected.has(participant.id); return <label className={`split-person${checked ? " selected" : ""}`} key={participant.id}><input type="checkbox" checked={checked} onChange={(event) => setSelected((current) => { const next = new Set(current); if (event.target.checked) next.add(participant.id); else next.delete(participant.id); return next; })} /><Avatar name={participant.name} index={index} /><span>{participant.name}</span>{values.splitMode === "equal" ? <span /> : <input className="value-input" type="text" inputMode="decimal" value={splitValues[participant.id] || ""} onChange={(event) => setSplitValues((current) => ({ ...current, [participant.id]: event.target.value.replace(/[^0-9,.]/g, "") }))} aria-label={`${values.splitMode} för ${participant.name}`} />}</label>; })}</div><div className="split-summary">{selected.size} {selected.size === 1 ? "person" : "personer"} valda{values.splitMode === "equal" && selected.size && values.amount ? ` · cirka ${formatMoney(Math.round(kronorToOre(values.amount) / selected.size))} var` : values.splitMode === "percentage" ? ` · ${summaryTotal.toFixed(2).replace(/\.00$/, "")}% fördelat` : values.splitMode === "exact" ? ` · ${summaryTotal.toFixed(2).replace(".", ",")} kr fördelat` : ""}</div><p className="form-error" role="alert">{error}</p><button className="button primary wide dialog-submit" type="submit" disabled={busy}>{busy ? "Sparar…" : expense ? "Spara ändringar" : "Lägg till utgift"} <span>→</span></button></form></Modal>;
}
