import { useEffect, useRef, useState } from "react";
import { api } from "../../api/client";
import { Avatar } from "../../components/Avatar";
import { DialogHeader, Modal } from "../../components/Modal";
import type { Category, InvitationResult, Trip, User } from "../../types/models";
import { copyText } from "../../utils/browser";
import { formatDate } from "../../utils/format";
import type { PaymentPreset } from "./TripPage";

export function InviteDialog({ open, tripId, onClose, notify }: { open: boolean; tripId: number; onClose: () => void; notify: (message: string) => void }) {
  const [invitation, setInvitation] = useState<InvitationResult | null>(null);
  const create = async () => { try { const payload = await api<{ invitation: InvitationResult }>(`/api/trips/${tripId}/invitations`, { method: "POST", body: {} }); setInvitation({ ...payload.invitation, path: new URL(payload.invitation.path, location.origin).href }); } catch (error) { notify(error instanceof Error ? error.message : "Kunde inte skapa inbjudan"); } };
  return <Modal open={open} onClose={onClose}><DialogHeader eyebrow="Dela resan" title="Bjud in till resan" onClose={onClose} /><p className="muted">Länken gäller i 14 dagar. Visa QR-koden för vännen bredvid dig eller skicka länken.</p><button className="button primary wide" type="button" onClick={() => void create()}>Skapa säker inbjudan</button>{invitation && <div className="invite-output"><div className="invite-qr"><img src={invitation.qrDataUrl} alt="QR-kod för resans inbjudan" /><strong>Skanna för att gå med</strong><small>Öppna mobilkameran och rikta den mot koden.</small></div><label>Inbjudningslänk<input readOnly value={invitation.path} /></label><button className="button dark wide" onClick={() => void copyText(invitation.path).then(() => notify("Inbjudningslänken kopierades"))}>Kopiera länk</button>{invitation.expiresAt && <p className="muted">Gäller till {formatDate(invitation.expiresAt)}.</p>}</div>}</Modal>;
}

export function PersonDialog({ open, trip, onClose, onSaved, notify }: { open: boolean; trip: Trip; onClose: () => void; onSaved: () => Promise<void>; notify: (message: string) => void }) {
  const [results, setResults] = useState<User[]>([]); const [heading, setHeading] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const searchTimer = useRef(0); const searchRequestId = useRef(0);
  useEffect(() => { if (!open) return; void api<{ contacts: User[] }>("/api/contacts").then((payload) => { setResults(payload.contacts); setHeading("Sparade kontakter"); }).catch((caught) => notify(caught instanceof Error ? caught.message : "Kunde inte läsa kontakter")); }, [open, notify]);
  const search = (query: string) => {
    window.clearTimeout(searchTimer.current);
    searchTimer.current = window.setTimeout(() => {
      const requestId = ++searchRequestId.current;
      const request = query.trim().length < 2 ? api<{ contacts: User[] }>("/api/contacts").then((p) => ({ users: p.contacts, heading: "Sparade kontakter" })) : api<{ users: User[] }>(`/api/users/search?q=${encodeURIComponent(query.trim())}`).then((p) => ({ users: p.users, heading: "Sökresultat" }));
      void request.then((payload) => { if (requestId !== searchRequestId.current) return; setResults(payload.users); setHeading(payload.heading); });
    }, 250);
  };
  const added = new Set(trip.participants.map((participant) => participant.userId).filter(Boolean)); const available = results.filter((user) => !added.has(user.id));
  const add = async (body: Record<string, unknown>, success: string) => { if (busy) return; setBusy(true); try { await api(`/api/trips/${trip.id}/participants`, { method: "POST", body }); await onSaved(); onClose(); notify(success); } catch (caught) { setError(caught instanceof Error ? caught.message : "Kunde inte lägga till personen"); } finally { setBusy(false); } };
  return <Modal open={open} onClose={onClose}><DialogHeader eyebrow="Fyll på gänget" title="Lägg till en vän" onClose={onClose} /><label>Sök registrerad användare<input type="search" placeholder="Namn eller e-post" autoComplete="off" onChange={(event) => search(event.target.value)} /></label><div className="contact-results">{heading && <p className="result-heading">{heading}</p>}{available.length ? available.map((user, index) => <button className="contact-result" key={user.id} type="button" disabled={busy} onClick={() => void add({ userId: user.id }, "Vännen lades till och sparades som kontakt")}><Avatar name={user.name} index={index} /><span><strong>{user.name}</strong><small>{user.email}</small></span><b>＋</b></button>) : <small className="muted">Ingen tillgänglig användare hittades.</small>}</div><div className="form-divider"><span>eller lägg till som gäst</span></div><form className="nested-form" onSubmit={(event) => { event.preventDefault(); void add(Object.fromEntries(new FormData(event.currentTarget)), "Gästen lades till"); }}><label>Namn<input name="name" placeholder="Vännens namn" maxLength={60} required /></label><label>Swish-nummer<input name="swishPhone" inputMode="tel" placeholder="070 123 45 67" /><small>Valfritt. Behövs för förifylld Swish-betalning.</small></label><p className="form-error" role="alert">{error}</p><button className="button primary wide" type="submit" disabled={busy}>{busy ? "Lägger till…" : "Lägg till på resan"} <span>→</span></button></form></Modal>;
}

export function CategoryDialog({ open, categories, user, onClose, onChanged, notify }: { open: boolean; categories: Category[]; user: User; onClose: () => void; onChanged: (categories: Category[]) => void; notify: (message: string) => void }) {
  const [error, setError] = useState("");
  const create = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); try { const payload = await api<{ categories: Category[] }>("/api/categories", { method: "POST", body: Object.fromEntries(new FormData(event.currentTarget)) }); onChanged(payload.categories); event.currentTarget.reset(); notify("Kategorin skapades"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Kunde inte skapa kategorin"); } };
  const archive = async (category: Category) => { try { const payload = await api<{ categories: Category[] }>(`/api/categories/${category.id}`, { method: "PATCH", body: { archived: !category.archivedAt } }); onChanged(payload.categories); notify(category.archivedAt ? "Kategorin återställdes" : "Kategorin arkiverades"); } catch (caught) { notify(caught instanceof Error ? caught.message : "Kunde inte uppdatera kategorin"); } };
  return <Modal open={open} onClose={onClose}><DialogHeader eyebrow="Ordning på notan" title="Hantera kategorier" onClose={onClose} /><form className="category-create" onSubmit={create}><label className="emoji-field">Emoji<input name="emoji" maxLength={16} defaultValue="🧾" required /></label><label className="grow">Namn<input name="name" maxLength={40} placeholder="t.ex. Fika" required /></label><button className="button primary" type="submit">Lägg till</button><p className="form-error" role="alert">{error}</p></form><div className="category-list">{categories.map((category) => { const canChange = !category.isBuiltin && (user.isAdmin || category.createdBy === user.id); return <article className={`category-row${category.archivedAt ? " category-archived" : ""}`} key={category.id}><span className="category-icon">{category.emoji}</span><span><strong>{category.name}</strong><small>{category.isBuiltin ? "Standardkategori" : category.archivedAt ? "Arkiverad" : "Egen kategori"}</small></span>{canChange && <button className="button ghost small-button" onClick={() => void archive(category)}>{category.archivedAt ? "Återställ" : "Arkivera"}</button>}</article>; })}</div><p className="muted">Arkiverade kategorier ligger kvar på gamla utgifter men kan inte väljas för nya.</p></Modal>;
}

export function PaymentDialog({ open, trip, preset, onClose, onSaved }: { open: boolean; trip: Trip; preset: PaymentPreset | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); if (!preset) return null;
  const person = (id: number) => trip.participants.find((item) => item.id === id)?.name || "Okänd";
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (busy) return; setError(""); setBusy(true); try { await api(`/api/trips/${trip.id}/payments`, { method: "POST", body: { ...Object.fromEntries(new FormData(event.currentTarget)), fromId: preset.fromId, toId: preset.toId } }); await onSaved(); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Kunde inte registrera betalningen"); } finally { setBusy(false); } };
  return <Modal open={open} onClose={onClose}><form onSubmit={submit}><DialogHeader eyebrow="Betalningen skickad?" title="Registrera betalning" onClose={onClose} /><p className="payment-route">{person(preset.fromId)} → {person(preset.toId)}</p><label>Belopp (SEK)<input name="amount" type="number" min="0.01" step="0.01" defaultValue={(preset.amountCents / 100).toFixed(2)} required /></label><label>Anteckning<input name="note" maxLength={120} placeholder="Swish-betalning" /></label><p className="form-error" role="alert">{error}</p><button className="button primary wide" type="submit" disabled={busy}>{busy ? "Registrerar…" : "Markera som betald"} <span>✓</span></button></form></Modal>;
}
