import { Avatar } from "../../components/Avatar";
import { EmptyState } from "../../components/EmptyState";
import type { AdminResponse } from "../../types/models";
import { formatDate, formatMoney } from "../../utils/format";

const activityLabels: Record<string, string> = {
  "account.bootstrap": "Administratörskonto skapades", "trip.created": "Grupp skapades", "trip.archived": "Grupp arkiverades", "trip.restored": "Grupp återställdes", "trip.deleted": "Grupp flyttades till papperskorgen", "trip.undeleted": "Grupp återställdes från papperskorgen", "participant.added": "Person lades till", "expense.created": "Utgift skapades", "expense.updated": "Utgift redigerades", "expense.voided": "Utgift togs bort från beräkningen", "receipt.created": "Kvitto laddades upp", "receipt.deleted": "Kvitto togs bort", "category.created": "Kategori skapades", "category.updated": "Kategori uppdaterades", "payment.created": "Betalning registrerades", "payment.voided": "Betalning togs bort från beräkningen", "invitation.created": "Inbjudan skapades", "invitation.joined": "Inbjudan användes", "friend_invitation.created": "Väninbjudan skapades", "friend_invitation.joined": "Väninbjudan användes", "admin.user.updated": "Användarkonto uppdaterades", "quick_tab.deleted": "Snabbnota togs bort",
};

interface Props {
  data: AdminResponse;
  currentUserId: number;
  demoMode: boolean;
  onEnterDemo: () => void;
  onBack: () => void;
  onRefresh: () => void;
  onOpenTrip: (id: number) => void;
  onUserUpdate: (id: number, update: { isAdmin?: boolean; isDisabled?: boolean }) => void;
  onTripArchive: (id: number, archived: boolean) => void;
  onTripRestore: (id: number) => void;
  onQuickTabDelete: (id: number) => void;
}

export function AdminPage({ data, currentUserId, demoMode, onEnterDemo, onBack, onRefresh, onOpenTrip, onUserUpdate, onTripArchive, onTripRestore, onQuickTabDelete }: Props) {
  return <section className="admin-view">
    <header className="dashboard-heading"><div><button className="mobile-back visible-back" onClick={onBack}>← Till startsidan</button><p className="eyebrow">Appadministration</p><h1>Hela Kompis Split</h1><p>Användare, grupper och aktivitet. Alla åtgärder kontrolleras på servern.</p></div><div className="header-actions"><button className="button ghost" disabled={demoMode} onClick={onEnterDemo} title={demoMode ? "Redan i demoläge" : "Visa appen med fiktiva exempeldata utan att röra riktiga konton"}>Demoläge</button><button className="button ghost" onClick={onRefresh}>Uppdatera</button></div></header>
    <div className="summary-grid admin-stats"><article className="hero-stat coral"><span className="stat-icon">●</span><p>Användare</p><strong>{data.stats.userCount}</strong><small>{data.stats.activeUserCount} aktiva</small></article><article className="hero-stat cobalt"><span className="stat-icon">✦</span><p>Grupper</p><strong>{data.stats.tripCount}</strong><small>{data.stats.activeTripCount} aktiva · {data.stats.deletedTripCount} borttagna</small></article><article className="member-stat"><p>Registrerade utgifter</p><strong>{formatMoney(data.stats.totalCents)}</strong><small>över hela appen</small></article></div>
    <section className="panel admin-panel"><div className="panel-title"><div><p className="eyebrow">Konton</p><h2>Alla användare</h2></div></div><div className="admin-list">{data.users.length ? data.users.map((user, index) => { const self = user.id === currentUserId; return <article className={`admin-row${user.isDisabled ? " disabled-row" : ""}`} key={user.id}><Avatar name={user.name} index={index} /><div className="admin-row-main"><strong>{user.name} {user.isAdmin && <span className="role-badge">Admin</span>}</strong><small>{user.email} · {user.tripCount} grupper · konto {formatDate(user.createdAt)}</small></div><div className="admin-actions"><button className="button ghost small-button" disabled={self} onClick={() => onUserUpdate(user.id, { isAdmin: !user.isAdmin })}>{user.isAdmin ? "Ta bort admin" : "Gör till admin"}</button><button className={`button ghost small-button ${user.isDisabled ? "positive" : "danger"}`} disabled={self} onClick={() => confirm(user.isDisabled ? "Aktivera kontot igen?" : "Inaktivera kontot och logga ut användaren från alla enheter?") && onUserUpdate(user.id, { isDisabled: !user.isDisabled })}>{user.isDisabled ? "Aktivera" : "Inaktivera"}</button></div></article>; }) : <EmptyState title="Inga användare">Användarkonton visas här.</EmptyState>}</div></section>
    <section className="panel admin-panel"><div className="panel-title"><div><p className="eyebrow">Överblick</p><h2>Alla grupper</h2></div></div><div className="admin-list">{data.trips.length ? data.trips.map((trip, index) => <article className={`admin-row${trip.deletedAt ? " disabled-row" : ""}`} key={trip.id}><span className="trip-emoji">{["✦", "⌁", "◇", "◉"][index % 4]}</span><div className="admin-row-main"><strong>{trip.name} {trip.deletedAt ? <span className="role-badge danger-badge">Borttagen</span> : trip.archivedAt ? <span className="role-badge muted-badge">Arkiverad</span> : null}</strong><small>{trip.ownerName || "Okänd ägare"} · {trip.memberCount} medlemmar · {trip.expenseCount} utgifter · {formatMoney(trip.totalCents)}</small></div><div className="admin-actions">{trip.deletedAt ? <button className="button ghost small-button positive" onClick={() => confirm("Återställ gruppen från papperskorgen?") && onTripRestore(trip.id)}>Återställ</button> : <><button className="button ghost small-button" onClick={() => onOpenTrip(trip.id)}>Öppna</button><button className="button ghost small-button" onClick={() => confirm(trip.archivedAt ? "Återställ gruppen?" : "Arkivera gruppen? Alla ekonomiska poster bevaras.") && onTripArchive(trip.id, !trip.archivedAt)}>{trip.archivedAt ? "Återställ" : "Arkivera"}</button></>}</div></article>) : <EmptyState title="Inga grupper">Alla grupper visas här när de skapas.</EmptyState>}</div></section>
    <section className="panel admin-panel"><div className="panel-title"><div><p className="eyebrow">Dela direkt</p><h2>Alla snabbnotor</h2></div></div><div className="admin-list">{data.quickTabs.length ? data.quickTabs.map((tab) => <article className="admin-row" key={tab.id}><span className="trip-emoji">●</span><div className="admin-row-main"><strong>{tab.name} {tab.closedAt && <span className="role-badge muted-badge">Avslutad</span>}</strong><small>{tab.ownerName || "Okänd ägare"} · {tab.merchant || "Ingen plats angiven"} · {tab.memberCount} deltagare · {formatMoney(tab.totalCents)}</small></div><div className="admin-actions"><button className="button ghost small-button danger" onClick={() => confirm(`Ta bort snabbnotan "${tab.name}" permanent? Detta kan inte ångras.`) && onQuickTabDelete(tab.id)}>Ta bort</button></div></article>) : <EmptyState title="Inga snabbnotor">Alla snabbnotor visas här när de skapas.</EmptyState>}</div></section>
    <section className="panel admin-panel"><div className="panel-title"><div><p className="eyebrow">Spårbarhet</p><h2>Senaste aktivitet</h2></div></div><div className="admin-list">{data.activity.length ? data.activity.map((item) => <article className="activity-row" key={item.id}><span className="activity-dot" /><div><strong>{activityLabels[item.action] || item.action}</strong><small>{item.actorName || "Systemet"}{item.tripName ? ` · ${item.tripName}` : ""} · {formatDate(item.createdAt)}</small></div></article>) : <EmptyState title="Ingen aktivitet">Administrativa och ekonomiska händelser visas här.</EmptyState>}</div></section>
  </section>;
}
